import subprocess
from pathlib import Path
import shutil
import tempfile
import os
from typing import Optional
import logging

logger = logging.getLogger(__name__)

class LatexBuilder:
    """Handles LaTeX document creation and compilation"""
    
    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = output_dir or Path('outputs')
        self.output_dir.mkdir(exist_ok=True)
        
        # LaTeX document template
        self.latex_template = r"""\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{graphicx}
\usepackage{enumitem}
\usepackage[margin=1in]{geometry}
\usepackage{parskip}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{booktabs}
\usepackage{array}

% Custom colors
\definecolor{notecolor}{RGB}{41, 128, 185}
\definecolor{questioncolor}{RGB}{39, 174, 96}

% Custom commands
\newcommand{\keyword}[1]{\textbf{\textcolor{notecolor}{#1}}}
\newcommand{\important}[1]{\textit{\textcolor{red}{#1}}}

% List settings
\setlist[enumerate]{itemsep=4pt, topsep=8pt}
\setlist[itemize]{itemsep=2pt, topsep=6pt}

\title{{{title}}}
\author{{Generated by AI Study Assistant}}
\date{{\today}}

\begin{document}

\maketitle
\tableofcontents
\newpage

{content}

% Footer
\vfill
\begin{center}
\small Generated on \today\ from source material.
\end{center}

\end{document}"""
    
    def create_latex_file(self, content: str, filename: str, title: str = "Study Notes") -> Path:
        """
        Create a complete LaTeX file from content
        Returns: Path to created .tex file
        """
        # Ensure filename has .tex extension
        if not filename.endswith('.tex'):
            filename += '.tex'
        
        tex_path = self.output_dir / filename
        
        # Replace placeholders in template
        latex_doc = self.latex_template.format(
            title=title,
            content=content
        )
        
        # Write to file
        with open(tex_path, 'w', encoding='utf-8') as f:
            f.write(latex_doc)
        
        logger.info(f"LaTeX file created: {tex_path}")
        return tex_path
    
    def compile_to_pdf(self, tex_path: Path) -> Path:
        """
        Compile LaTeX file to PDF
        Returns: Path to generated PDF
        """
        if not tex_path.exists():
            raise FileNotFoundError(f"LaTeX file not found: {tex_path}")
        
        # Check if LaTeX compiler is available
        if not self.check_latex_available():
            raise RuntimeError("LaTeX compiler (pdflatex) not found. Install TeX Live or MiKTeX.")
        
        # Create temporary directory for compilation
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_tex = Path(temp_dir) / tex_path.name
            
            # Copy .tex file to temp directory
            shutil.copy(tex_path, temp_tex)
            
            # Run pdflatex (multiple runs for references)
            for i in range(2):  # Run twice for proper references
                result = subprocess.run(
                    [
                        'pdflatex',
                        '-interaction=nonstopmode',
                        '-output-directory', temp_dir,
                        str(temp_tex)
                    ],
                    capture_output=True,
                    text=True
                )
                
                if result.returncode != 0:
                    logger.error(f"LaTeX compilation error (run {i+1}): {result.stderr}")
                    if i == 0:  # Only raise on first run failure
                        raise RuntimeError(f"LaTeX compilation failed:\n{result.stderr}")
            
            # Define PDF path
            pdf_name = tex_path.stem + '.pdf'
            pdf_path = self.output_dir / pdf_name
            
            # Move PDF to output directory
            temp_pdf = Path(temp_dir) / pdf_name
            if temp_pdf.exists():
                shutil.move(temp_pdf, pdf_path)
                
                # Clean up auxiliary files
                for aux_file in Path(temp_dir).glob(f"{tex_path.stem}.*"):
                    if aux_file.suffix not in ['.pdf', '.tex']:
                        aux_file.unlink(missing_ok=True)
                
                logger.info(f"PDF compiled successfully: {pdf_path}")
                return pdf_path
            else:
                raise RuntimeError("PDF was not generated")
    
    def check_latex_available(self) -> bool:
        """Check if LaTeX compiler is available"""
        try:
            result = subprocess.run(
                ['pdflatex', '--version'],
                capture_output=True,
                text=True
            )
            return result.returncode == 0
        except (subprocess.SubprocessError, FileNotFoundError):
            return False
    
    def get_available_compilers(self) -> list:
        """Get list of available LaTeX compilers"""
        compilers = ['pdflatex', 'xelatex', 'lualatex']
        available = []
        
        for compiler in compilers:
            try:
                subprocess.run([compiler, '--version'], 
                             capture_output=True, 
                             check=False)
                available.append(compiler)
            except (subprocess.SubprocessError, FileNotFoundError):
                pass
        
        return available